# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25560b049fb982624af77e5504acef8c9e3ee98007bd653fd735d142e36d5eb3d63114fd61b5879ff7e2ea39cac6b36337851ed9b72dac8dd0f15279cab13d3c

test:
  secret_key_base: a8cfcee69eb1631bdec78f9a49936bad4b4cb8edab5a7d8876f047eaa98216a9dffa0a421cce3511c15032e8d30f8e706050d825acf5d3266c912af9c949de65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
