#Create a User first

new_user = User.create(email: "test@test.com", password: "123456", password_confirmation: "123456")
puts 'User created'

#Create 10 cars then

Car.create(photo: "https://images.unsplash.com/photo-1485291571150-772bcfc10da5?auto=format&fit=crop&w=1600&q=60&ixid=dW5zcGxhc2guY29tOzs7Ozs%3D", make: "Mercedes", model: "CLS 63", seats: "5", engine_size: "6", transmission: "auto", color: "White", price: "100",  description: "The Mercedes-Benz CLS is a mid-size luxury 4-door sedan (fastback), originally launched in 2005 and based on the W211 E-Class and was internally designated as the W219. The second generation CLS-Class was introduced in September 2010 and production started in the beginning of 2011. The CLS slots above the E-Class and below the S-Class.", user: new_user)
Car.create(photo: "https://images.unsplash.com/photo-1441148345475-03a2e82f9719?auto=format&fit=crop&w=1650&q=60&ixid=dW5zcGxhc2guY29tOzs7Ozs%3D", make: "BMW", model: "M3", seats: "4", engine_size: "5", transmission: "auto", color: "Grey", price: "80",  description: "The BMW M4 is a high-performance version of the BMW 4 Series automobile developed by BMW's motorsport division, the BMW M GmbH. Part of the renumbering that splits the 3 Series coupe and convertible models to the 4 Series (to further differentiate it from the 3 Series), the M4 replaced the M3 Coupe and Convertible models.", user: new_user)
Car.create(photo: "https://images.unsplash.com/photo-1506244856291-8910ea843e81?auto=format&fit=crop&w=1650&q=60&ixid=dW5zcGxhc2guY29tOzs7Ozs%3D", make: "Volvo", model: "V60", seats: "3", engine_size: "4", transmission: "auto", color: "Black", price: "60",  description: "The Volvo V60 is a five door wagon produced by Volvo Cars based on the S60 compact executive car. This vehicle was released in 2011 and redesigned for the model year of 2014.", user: new_user)
Car.create(photo: "https://www.autocar.co.uk/sites/autocar.co.uk/files/styles/gallery_slide/public/volkswagen-golf-r.jpg?itok=ufJeULGg", make: "VW", model: "Golf R", seats: "5", engine_size: "3", transmission: "auto", color: "Space Grey", price: "70",  description: "The Volkswagen Golf (About this sound listen (help·info)) is a small family car produced by the German manufacturer Volkswagen since 1974, marketed worldwide across seven generations, in various body configurations and under various nameplates – such as the Volkswagen Rabbit in the United States and Canada (Mk1 and Mk5), and as the Volkswagen Caribe in Mexico (Mk1).", user: new_user)
Car.create(photo: "https://images.unsplash.com/photo-1502161254066-6c74afbf07aa?auto=format&fit=crop&w=1651&q=60&ixid=dW5zcGxhc2guY29tOzs7Ozs%3D", make: "Audi", model: "RS8", seats: "4", engine_size: "8", transmission: "auto", color: "Brown", price: "50",  description: "The Audi R8[2] (Typ 42)[3] is a mid-engine, 2-seater sports car,[2][4] which uses Audi's trademark quattro permanent all-wheel drive system.[2][5] It was introduced by the German car manufacturer Audi AG in 2006.", user: new_user)
Car.create(photo: "https://images.unsplash.com/photo-1501987584265-0b7af0e74421?auto=format&fit=crop&w=1650&q=60&ixid=dW5zcGxhc2guY29tOzs7Ozs%3D", make: "Mitsubishi", model: "Lancer", seats: "2", engine_size: "6", transmission: "auto", color: "Purple", price: "40",  description: "The Mitsubishi Outlander is a mid-size crossover manufactured by Japanese automaker Mitsubishi. It was originally known as the Mitsubishi Airtrek when it was introduced in Japan in 2001, and was based on the Mitsubishi ASX concept vehicle exhibited at the 2001 North American International Auto Show.", user: new_user)
Car.create(photo: "https://www.nissan-cdn.net/content/dam/Nissan/za/vehicles/FY17GT-R/Minorchange/overview/17TDIeurhd_GTRHelios016.jpg.ximg.l_full_m.smart.jpg", make: "Nissan", model: "GTR", seats: "5", engine_size: "1", transmission: "auto", color: "Pink", price: "30",  description: "The Nissan GT-R is a 2-door 2+2 high performance vehicle produced by Nissan unveiled in 2007.[2][3][4] It is the successor to the Nissan Skyline GT-R although no longer part of the Skyline range itself, the name having been given over to the R35 Series and having since left its racing roots.", user: new_user)
Car.create(photo: "https://media.ed.edmunds-media.com/porsche/911/2014/oem/2014_porsche_911_coupe_targa-4s_fq_oem_1_1280.jpg", make: "Porsche", model: "911 Sports", seats: "2", engine_size: "5", transmission: "auto", color: "Red", price: "100",  description: "The Porsche 911 (pronounced Nine Eleven or German: Neunelfer) is a two-door, 2+2 high performance classic German sports car made since 1963[1] by Porsche AG of Stuttgart, Germany. It has a rear-mounted six cylinder boxer engine and all round independent suspension. It has undergone continuous development, though the basic concept has remained little changed.[2]", user: new_user)
Car.create(photo: "https://hips.hearstapps.com/amv-prod-cad-assets.s3.amazonaws.com/images/10q1/319791/2011-mini-countryman-photo-322421-s-original.jpg", make: "Mini", model: "Countryman", seats: "5", engine_size: "2", transmission: "auto", color: "Orange", price: "20",  description: "he Mini is a small economy car produced by the English-based British Motor Corporation (BMC) and its successors from 1959 until 2000. The original is considered an icon of 1960s British popular culture.[8][9][10][11]", user: new_user)


puts "created 10 cars"
